"""
Dynamic quick-topic suggestions based on grade + subject.
Covers LKG → Class 12 across all subjects.
"""

# ── Concept / Quiz topics  (grade, subject) → list[6] ────────────────────────
_CONCEPT_TOPICS = {

    # ── LKG ──────────────────────────────────────────────────────────────────
    ("LKG", "General"):      ["Colors & Shapes", "Numbers 1–10", "Animals Around Us",
                              "Fruits & Vegetables", "My Body Parts", "My Family"],

    # ── UKG ──────────────────────────────────────────────────────────────────
    ("UKG", "General"):      ["Alphabets A–Z", "Numbers 1–50", "Days of the Week",
                              "Seasons & Weather", "Means of Transport", "Plants & Trees"],

    # ── Class 1 ──────────────────────────────────────────────────────────────
    ("1", "Science"):        ["My Family", "Parts of a Plant", "Animals & Their Homes",
                              "Food We Eat", "Uses of Water", "Our Five Senses"],
    ("1", "Mathematics"):    ["Numbers 1–100", "Addition Basics", "Subtraction Basics",
                              "Basic Shapes", "Simple Measurement", "Patterns"],
    ("1", "Hindi"):          ["वर्णमाला – स्वर", "वर्णमाला – व्यंजन", "सरल शब्द",
                              "मेरा परिचय", "रंग और आकार", "कविता पाठ"],
    ("1", "English"):        ["Alphabet A–Z", "Simple CVC Words", "My Body",
                              "Colours & Numbers", "Nursery Rhymes", "Simple Sentences"],
    ("1", "General"):        ["My Family", "Numbers 1–100", "Alphabet A–Z",
                              "Animals & Their Homes", "Colors & Shapes", "Food We Eat"],

    # ── Class 2 ──────────────────────────────────────────────────────────────
    ("2", "Science"):        ["Plants Around Us", "Animals: Tame & Wild", "Food & Nutrition",
                              "Uses of Water", "Air & Its Importance", "Seasons & Weather"],
    ("2", "Mathematics"):    ["Numbers up to 1000", "Addition with Carry", "Subtraction with Borrow",
                              "Multiplication Tables", "Simple Fractions", "Length & Weight"],
    ("2", "Hindi"):          ["संज्ञा", "सर्वनाम", "सरल क्रिया",
                              "सरल वाक्य", "छोटी कहानी", "पत्र लेखन"],
    ("2", "English"):        ["Nouns", "Pronouns", "Simple Verbs",
                              "Simple Sentences", "Story Reading", "Rhymes & Poems"],
    ("2", "General"):        ["Plants Around Us", "Numbers up to 1000", "Nouns",
                              "Animals: Tame & Wild", "Multiplication Tables", "Seasons & Weather"],

    # ── Class 3 ──────────────────────────────────────────────────────────────
    ("3", "Science"):        ["Parts of a Plant", "Animal Habitats", "Our Food & Health",
                              "Water Sources & Uses", "Air & Pollution", "Earth & Sky"],
    ("3", "Mathematics"):    ["4-Digit Numbers", "Multiplication", "Division Basics",
                              "Simple Fractions", "Perimeter", "Time & Calendar"],
    ("3", "Hindi"):          ["संज्ञा के भेद", "विशेषण", "क्रिया के प्रकार",
                              "विलोम शब्द", "पर्यायवाची शब्द", "अनुच्छेद लेखन"],
    ("3", "English"):        ["Parts of Speech", "Simple Tenses", "Articles (a an the)",
                              "Comprehension", "Letter Writing", "Vocabulary Building"],
    ("3", "Social Science"): ["Our Neighbourhood", "Community Helpers", "Maps & Directions",
                              "Our State", "Transport & Communication", "Festivals of India"],
    ("3", "General"):        ["Parts of a Plant", "4-Digit Numbers", "Parts of Speech",
                              "Animal Habitats", "Multiplication", "Our Neighbourhood"],

    # ── Class 4 ──────────────────────────────────────────────────────────────
    ("4", "Science"):        ["Parts of a Plant", "Food We Eat", "Animals & Habitats",
                              "Air and Water", "Simple Machines", "Our Environment"],
    ("4", "Mathematics"):    ["Addition & Subtraction", "Multiplication Tables", "Division Basics",
                              "Simple Fractions", "2D Shapes", "Measurement"],
    ("4", "Hindi"):          ["वर्णमाला", "संज्ञा और सर्वनाम", "विलोम शब्द",
                              "पर्यायवाची", "वाक्य रचना", "कहानी लेखन"],
    ("4", "English"):        ["Nouns & Pronouns", "Simple Sentences", "Action Words (Verbs)",
                              "Adjectives", "Story Reading", "Rhymes & Poems"],
    ("4", "Social Science"): ["Our Family & Community", "Our Neighbourhood", "Maps and Directions",
                              "Means of Transport", "Our Country India", "Festivals of India"],
    ("4", "General"):        ["Parts of a Plant", "Addition & Subtraction", "Our Family",
                              "Nouns & Pronouns", "Animals & Habitats", "Maps and Directions"],

    # ── Class 5 ──────────────────────────────────────────────────────────────
    ("5", "Science"):        ["Photosynthesis", "Food Chain", "Solar System",
                              "Human Body", "Properties of Water", "Simple Machines"],
    ("5", "Mathematics"):    ["Large Numbers", "Fractions", "Decimals",
                              "Area & Perimeter", "Angles in Shapes", "Roman Numerals"],
    ("5", "Hindi"):          ["संज्ञा", "विशेषण", "क्रिया",
                              "पत्र लेखन", "मुहावरे", "निबंध लेखन"],
    ("5", "English"):        ["Tenses (Present Past Future)", "Articles (a an the)", "Prepositions",
                              "Comprehension Skills", "Letter Writing", "Conjunctions"],
    ("5", "Social Science"): ["India on the Globe", "Freedom Struggle", "Natural Resources",
                              "Climate of India", "Soil and Agriculture", "State and Capital"],
    ("5", "General"):        ["Photosynthesis", "Fractions", "India on the Globe",
                              "Tenses", "Food Chain", "Angles in Shapes"],

    # ── Class 6 ──────────────────────────────────────────────────────────────
    ("6", "Science"):        ["Photosynthesis", "Food Chain & Web", "Motion & Measurement",
                              "Light & Shadows", "Water Cycle", "Components of Food"],
    ("6", "Mathematics"):    ["Knowing Our Numbers", "Fractions & Decimals", "Basic Algebra",
                              "Geometry: Lines & Angles", "Integers", "Ratio & Proportion"],
    ("6", "Hindi"):          ["संज्ञा के भेद", "विशेषण", "क्रिया के भेद",
                              "मुहावरे", "पत्र लेखन", "अनुच्छेद लेखन"],
    ("6", "English"):        ["Parts of Speech", "Simple Present Tense", "Reading Comprehension",
                              "Letter Writing", "Vocabulary Building", "Punctuation"],
    ("6", "Social Science"): ["Indus Valley Civilisation", "Globe & Latitudes", "India's Diversity",
                              "Panchayati Raj", "Rural & Urban Livelihoods", "The Earth & Solar System"],
    ("6", "General"):        ["Photosynthesis", "Knowing Our Numbers", "Indus Valley Civilisation",
                              "Parts of Speech", "Water Cycle", "Globe & Latitudes"],

    # ── Class 7 ──────────────────────────────────────────────────────────────
    ("7", "Science"):        ["Nutrition in Plants", "Heat & Temperature", "Motion & Time",
                              "Electric Current", "Acids Bases & Salts", "Weather Climate & Adaptations"],
    ("7", "Mathematics"):    ["Integers", "Fractions & Decimals", "Simple Equations",
                              "Lines & Angles", "Ratio & Proportion", "Percentage"],
    ("7", "Hindi"):          ["संधि", "समास", "काल के भेद",
                              "वाच्य", "अलंकार", "निबंध लेखन"],
    ("7", "English"):        ["Passive Voice", "Reported Speech", "Degrees of Adjective",
                              "Reading Comprehension", "Essay Writing", "Phrasal Verbs"],
    ("7", "Social Science"): ["Medieval Kingdoms", "Delhi Sultanate", "Mughal Empire",
                              "Tribals & Forests", "Water Resources", "Democratic Government"],
    ("7", "General"):        ["Nutrition in Plants", "Simple Equations", "Mughal Empire",
                              "Passive Voice", "Heat & Temperature", "Percentage"],

    # ── Class 8 ──────────────────────────────────────────────────────────────
    ("8", "Science"):        ["Crop Production", "Microorganisms", "Metals & Non-metals",
                              "Cell Structure", "Combustion & Flame", "Friction"],
    ("8", "Mathematics"):    ["Rational Numbers", "Linear Equations in One Variable", "Squares & Square Roots",
                              "Mensuration", "Quadrilaterals", "Data Handling"],
    ("8", "Hindi"):          ["संधि विच्छेद", "समास", "रस और छंद",
                              "अपठित गद्यांश", "पत्र लेखन", "व्याकरण अभ्यास"],
    ("8", "English"):        ["Modals (can could may)", "Compound & Complex Sentences", "Idioms & Phrases",
                              "Formal Letter Writing", "Active & Passive Voice", "Reported Speech"],
    ("8", "Social Science"): ["Colonialism in India", "Industries & Trade", "Natural Resources",
                              "The Indian Constitution", "The Judiciary", "Social Issues"],
    ("8", "General"):        ["Microorganisms", "Linear Equations", "The Indian Constitution",
                              "Modals", "Cell Structure", "Squares & Square Roots"],

    # ── Class 9 ──────────────────────────────────────────────────────────────
    ("9", "Science"):        ["Matter in Our Surroundings", "Motion (Speed & Velocity)", "Force & Newton's Laws",
                              "Gravitation", "Work Energy Power", "Sound Waves"],
    ("9", "Mathematics"):    ["Number Systems (Irrational Numbers)", "Polynomials", "Coordinate Geometry",
                              "Triangle Congruence", "Circles & Chords", "Heron's Formula"],
    ("9", "Hindi"):          ["क्षितिज काव्य खंड", "गद्य साहित्य", "अपठित बोध",
                              "व्याकरण – काल", "पत्र और निबंध", "संचार माध्यम"],
    ("9", "English"):        ["Tenses Review", "The Fun They Had", "The Sound of Music",
                              "Modals & Conditionals", "Reported Speech", "Writing a Report"],
    ("9", "Social Science"): ["French Revolution", "Socialism & Russian Revolution", "Nazism & Hitler",
                              "Forest Society & Colonialism", "Electoral Politics", "Drainage of India"],
    ("9", "General"):        ["Newton's Laws of Motion", "Polynomials", "French Revolution",
                              "The Fun They Had", "Matter in Our Surroundings", "Coordinate Geometry"],

    # ── Class 10 ─────────────────────────────────────────────────────────────
    ("10", "Science"):       ["Chemical Reactions & Equations", "Acids Bases & Salts", "Metals & Non-metals",
                              "Life Processes", "Electricity & Circuits", "Heredity & Evolution"],
    ("10", "Mathematics"):   ["Real Numbers", "Polynomials", "Quadratic Equations",
                              "Trigonometry Basics", "Circles & Tangents", "Probability"],
    ("10", "Hindi"):         ["सूरदास के पद", "तुलसीदास – रामचरितमानस", "मीराबाई",
                              "काव्य सौंदर्य", "वितान गद्य", "संदेश लेखन"],
    ("10", "English"):       ["Nelson Mandela", "From the Diary of Anne Frank", "Letter Writing (Formal)",
                              "The Midnight Visitor", "Grammar: Determiners", "Speech Writing"],
    ("10", "Social Science"):["Nationalism in India", "Federalism", "Democracy & Diversity",
                              "Economic Development", "Consumer Rights & Protection", "Resources & Development"],
    ("10", "General"):       ["Chemical Reactions", "Real Numbers", "Nationalism in India",
                              "Nelson Mandela", "Life Processes", "Quadratic Equations"],

    # ── Class 11 ─────────────────────────────────────────────────────────────
    ("11", "Physics"):       ["Motion in a Straight Line", "Newton's Laws of Motion", "Work Energy Power",
                              "Gravitation", "Thermodynamics", "Waves & Sound"],
    ("11", "Chemistry"):     ["Structure of Atom", "Chemical Bonding & Molecular Structure", "Thermodynamics",
                              "Chemical Equilibrium", "Redox Reactions", "Hydrocarbons"],
    ("11", "Biology"):       ["Cell: The Unit of Life", "Biomolecules", "Cell Division (Mitosis & Meiosis)",
                              "Photosynthesis in Higher Plants", "Respiration in Plants", "Neural Control & Coordination"],
    ("11", "Mathematics"):   ["Sets & Relations", "Trigonometric Functions", "Complex Numbers",
                              "Sequences & Series", "Limits & Derivatives", "Permutations & Combinations"],
    ("11", "Economics"):     ["Introduction to Microeconomics", "Consumer Equilibrium & Demand",
                              "Theory of Production & Cost", "Forms of Market", "National Income Basics", "Money & Banking"],
    ("11", "Computer Science"):["Python Fundamentals", "Data Types & Variables", "Control Structures (if for while)",
                              "Functions in Python", "Lists Tuples & Dictionaries", "File Handling"],
    ("11", "Business Studies"):["Nature & Significance of Business", "Forms of Business Organisation",
                              "Private Public & Global Enterprises", "Business Services",
                              "Emerging Modes of Business", "Social Responsibility of Business"],
    ("11", "History"):       ["Early Societies", "Writing & City Life (Mesopotamia)", "Nomadic Empires",
                              "The Three Orders (Medieval Europe)", "Changing Cultural Traditions", "Displacing Indigenous Peoples"],
    ("11", "Political Science"):["Constitution: Why & How", "Rights in the Indian Constitution",
                              "Election & Representation", "Executive (President PM Cabinet)",
                              "Legislature (Parliament)", "Judiciary (Supreme Court)"],
    ("11", "English"):       ["The Portrait of a Lady", "A Photograph", "We're Not Afraid to Die",
                              "Discovering Tut", "Voice of the Rain", "Writing Skills: Report"],
    ("11", "Hindi"):         ["नमक का दारोगा", "मियाँ नसीरुद्दीन", "आलो-आँधारि",
                              "बात सीधी थी पर", "पद्य – कबीर के पद", "व्याकरण – संधि समास"],
    ("11", "Social Science"):["Physical Features of India", "Climate of India", "Natural Vegetation",
                              "Indian Economy at Independence", "Liberalisation & Globalisation", "Human Development"],
    ("11", "General"):       ["Newton's Laws of Motion", "Chemical Bonding", "Cell Biology",
                              "Trigonometry", "Consumer Theory", "Python Fundamentals"],

    # ── Class 12 ─────────────────────────────────────────────────────────────
    ("12", "Physics"):       ["Electric Charges & Fields (Coulomb's Law)", "Current Electricity (Ohm's Law)",
                              "Magnetic Effects of Current", "Electromagnetic Induction",
                              "Ray Optics & Optical Instruments", "Dual Nature of Radiation & Matter"],
    ("12", "Chemistry"):     ["Solid State", "Solutions & Colligative Properties", "Electrochemistry",
                              "Chemical Kinetics", "Coordination Compounds", "Biomolecules & Polymers"],
    ("12", "Biology"):       ["Sexual Reproduction in Flowering Plants", "Human Reproduction",
                              "Principles of Inheritance (Mendel)", "Molecular Basis of Inheritance (DNA)",
                              "Biotechnology – Principles & Processes", "Ecosystem & Biodiversity"],
    ("12", "Mathematics"):   ["Relations & Functions", "Inverse Trigonometric Functions",
                              "Matrices & Determinants", "Continuity & Differentiability",
                              "Application of Derivatives", "Probability (Bayes' Theorem)"],
    ("12", "Economics"):     ["National Income Accounting", "Money Supply & Banking System",
                              "Income Determination (AD AS Model)", "Government Budget & Fiscal Policy",
                              "Balance of Payments", "Development Experience of India vs China vs Pakistan"],
    ("12", "Computer Science"):["Python: OOP Concepts", "Stack & Queue (DSA)", "Linked List",
                              "Database Concepts & SQL", "Computer Networks & Protocols", "Cybersecurity Basics"],
    ("12", "Business Studies"):["Nature & Significance of Management", "Principles of Management (Fayol Taylor)",
                              "Business Environment", "Planning & Decision Making",
                              "Marketing Management (4Ps)", "Consumer Protection Act"],
    ("12", "History"):       ["Bricks Beads & Bones (Harappa)", "Kings Farmers & Towns",
                              "Kinship Caste & Class", "Bhakti Sufi Traditions",
                              "Rebels & the Raj (1857)", "Framing the Constitution"],
    ("12", "Political Science"):["The Cold War Era", "The End of Bipolarity", "US Hegemony",
                              "Alternative Centres of Power (EU China)", "Popular Movements in India",
                              "Rise of New Social Movements"],
    ("12", "English"):       ["The Last Lesson", "Lost Spring", "Deep Water",
                              "The Rattrap", "My Mother at Sixty-six", "Going Places"],
    ("12", "Hindi"):         ["भक्तिन", "बाज़ार दर्शन", "काले मेघा पानी दे",
                              "पहलवान की ढोलक", "सिल्वर वेडिंग", "जूझ"],
    ("12", "Social Science"):["Globalisation & Its Impact", "Social Movements", "Cultural Change",
                              "The Market as a Social Institution", "Environment & Society", "Agrarian Society & Change"],
    ("12", "General"):       ["Electric Charges & Coulomb's Law", "Electrochemistry", "Genetics (Mendel's Laws)",
                              "Application of Derivatives", "National Income Accounting", "SQL Databases"],
}


# ── Activity suggestions (grade, subject) → list[4] ──────────────────────────
_ACTIVITY_TOPICS = {

    # ── LKG ──────────────────────────────────────────────────────────────────
    ("LKG", "General"):      ["Color Sorting Game", "Shape Recognition Activity",
                              "Number Counting with Objects", "Animal Sound Game"],

    # ── UKG ──────────────────────────────────────────────────────────────────
    ("UKG", "General"):      ["Alphabet Writing Practice", "Number Order Game",
                              "Season Drawing Activity", "Transport Sorting Game"],

    # ── Class 1 ──────────────────────────────────────────────────────────────
    ("1", "Science"):        ["Plant a Seed Observation", "Five Senses Activity",
                              "Animal Matching Game", "Water Uses Experiment"],
    ("1", "Mathematics"):    ["Number Line Walk", "Shape Hunt in Classroom",
                              "Counting Objects Game", "Pattern Making Activity"],
    ("1", "Hindi"):          ["वर्णमाला गायन", "शब्द बनाओ खेल",
                              "कविता पाठ", "चित्र देखो बताओ"],
    ("1", "English"):        ["Alphabet Song & Writing", "Word Building with Cards",
                              "Story Telling Circle", "Poem Recitation"],
    ("1", "General"):        ["Plant a Seed Observation", "Number Line Walk",
                              "Shape Hunt in Classroom", "Five Senses Activity"],

    # ── Class 2 ──────────────────────────────────────────────────────────────
    ("2", "Science"):        ["Food Group Sorting Activity", "Water Cycle Drawing",
                              "Animal Habitat Matching", "Air Experiment with Balloon"],
    ("2", "Mathematics"):    ["Skip Counting Game", "Addition with Abacus/Stones",
                              "Fraction of Shapes Activity", "Weight Measurement Activity"],
    ("2", "Hindi"):          ["संज्ञा शब्द संग्रह", "वाक्य निर्माण खेल",
                              "कहानी सुनाओ", "कविता पाठ प्रतियोगिता"],
    ("2", "English"):        ["Noun Hunt in Classroom", "Verb Action Game",
                              "Story Sequencing Cards", "Simple Sentence Making"],
    ("2", "General"):        ["Food Group Sorting", "Skip Counting Game",
                              "Noun Hunt Activity", "Water Cycle Drawing"],

    # ── Class 3 ──────────────────────────────────────────────────────────────
    ("3", "Science"):        ["Plant Parts Labeling Activity", "Habitat Diorama Making",
                              "Water Purification Demo", "Weather Observation Chart"],
    ("3", "Mathematics"):    ["Multiplication Table Race", "Fraction Pizza Activity",
                              "Perimeter Measurement Walk", "Calendar Activity"],
    ("3", "Hindi"):          ["विलोम शब्द खेल", "पर्यायवाची मिलाओ",
                              "अनुच्छेद लेखन", "कहानी नाटक"],
    ("3", "English"):        ["Tense Changing Game", "Article Fill-in Activity",
                              "Comprehension Race", "Letter Writing Practice"],
    ("3", "Social Science"): ["Draw Your Neighbourhood Map", "Community Helper Role Play",
                              "Festival Collage Making", "Transport Sorting Activity"],
    ("3", "General"):        ["Plant Parts Labeling", "Multiplication Table Race",
                              "Draw Neighbourhood Map", "Tense Changing Game"],

    # ── Class 4 ──────────────────────────────────────────────────────────────
    ("4", "Science"):        ["Leaf Rubbings Activity", "Plant a Seed Experiment",
                              "Water Evaporation Demo", "Animal Sorting Game"],
    ("4", "Mathematics"):    ["Skip Counting with Stones", "Shape Hunt in Classroom",
                              "Fraction Pizza Activity", "Measurement with Rulers"],
    ("4", "Hindi"):          ["कविता पाठ प्रतियोगिता", "शब्द निर्माण खेल",
                              "कहानी सुनाओ", "वर्णमाला गेम"],
    ("4", "English"):        ["Story Telling Circle", "Word Building Game",
                              "Sentence Making Activity", "Poem Recitation"],
    ("4", "Social Science"): ["Draw Your Neighbourhood Map", "Family Tree Activity",
                              "Transport Sorting Game", "Festival Collage"],
    ("4", "General"):        ["Plant a Seed Experiment", "Shape Hunt in Classroom",
                              "Draw Your Neighbourhood Map", "Story Telling Circle"],

    # ── Class 5 ──────────────────────────────────────────────────────────────
    ("5", "Science"):        ["Food Chain Drawing Activity", "Solar System Model",
                              "Water Cycle in a Bag", "Simple Machine Hunt"],
    ("5", "Mathematics"):    ["Fraction Pizza with Paper", "Area with Graph Paper",
                              "Decimal Shopping Game", "Angle Measuring Activity"],
    ("5", "Hindi"):          ["पत्र लेखन अभ्यास", "मुहावरे पर नाटक",
                              "कविता रचना", "समाचार वाचन"],
    ("5", "English"):        ["Letter Writing Practice", "Tense Changing Game",
                              "Story Sequencing", "Debate Activity"],
    ("5", "Social Science"): ["India Map Labelling", "Freedom Fighter Role Play",
                              "Climate Chart Making", "State Capital Quiz Game"],
    ("5", "General"):        ["Food Chain Drawing", "Fraction Pizza with Paper",
                              "India Map Labelling", "Letter Writing Practice"],

    # ── Class 6 ──────────────────────────────────────────────────────────────
    ("6", "Science"):        ["Photosynthesis Diagram Activity", "Food Web Making",
                              "Shadow Length Experiment", "Water Purification Demo"],
    ("6", "Mathematics"):    ["Integer Number Line Game", "Fraction Strip Activity",
                              "Geometry Shapes Drawing", "Data Collection & Bar Graph"],
    ("6", "Hindi"):          ["मुहावरे पर नाटक", "पत्र लेखन प्रतियोगिता",
                              "कविता पाठ", "संज्ञा शब्द संग्रह"],
    ("6", "English"):        ["Parts of Speech Sorting", "Newspaper Reading Activity",
                              "Debate on a Topic", "Creative Story Writing"],
    ("6", "Social Science"): ["Indus Valley Model Making", "Globe Observation Activity",
                              "Panchayat Role Play", "Map of India Drawing"],
    ("6", "General"):        ["Photosynthesis Diagram", "Integer Number Line Game",
                              "Globe Observation Activity", "Parts of Speech Sorting"],

    # ── Class 7 ──────────────────────────────────────────────────────────────
    ("7", "Science"):        ["Acid Base Indicator Test", "Nutrition in Plants Chart",
                              "Electric Circuit Building", "Heat Conduction Experiment"],
    ("7", "Mathematics"):    ["Equation Solving Race", "Percentage Discount Activity",
                              "Angle Bisector Drawing", "Ratio Recipe Activity"],
    ("7", "Hindi"):          ["समास पहचान खेल", "काल परिवर्तन अभ्यास",
                              "वाद-विवाद प्रतियोगिता", "अलंकार पहचान"],
    ("7", "English"):        ["Passive Voice Conversion", "Group Debate Activity",
                              "Phrasal Verb Matching Game", "Role Play: Reported Speech"],
    ("7", "Social Science"): ["Mughal Empire Timeline", "Water Conservation Poster",
                              "Democratic Process Role Play", "Medieval Trade Route Map"],
    ("7", "General"):        ["Acid Base Indicator Test", "Percentage Discount Activity",
                              "Mughal Empire Timeline", "Group Debate Activity"],

    # ── Class 8 ──────────────────────────────────────────────────────────────
    ("8", "Science"):        ["Crop Rotation Diagram", "Microorganism Observation",
                              "Metal Reactivity Series", "Cell Division Model"],
    ("8", "Mathematics"):    ["Rational Number Line Activity", "Mensuration of Classroom",
                              "Data Handling Survey", "Square Root Estimation"],
    ("8", "Hindi"):          ["अपठित गद्यांश विश्लेषण", "समास रचना खेल",
                              "रस पहचान प्रतियोगिता", "पत्र लेखन"],
    ("8", "English"):        ["Formal Letter Writing", "Idiom Illustration Activity",
                              "Active Passive Conversion Game", "Group Discussion"],
    ("8", "Social Science"): ["Constitution Study Circle", "Industry Location Map",
                              "Social Issues Debate", "Colonial History Timeline"],
    ("8", "General"):        ["Microorganism Chart", "Mensuration of Classroom",
                              "Constitution Study Circle", "Formal Letter Writing"],

    # ── Class 9 ──────────────────────────────────────────────────────────────
    ("9", "Science"):        ["Motion Graph Drawing", "Newton's Laws Demonstration",
                              "Sound Wave Experiment", "Gravitation Calculation"],
    ("9", "Mathematics"):    ["Coordinate Geometry Plotting", "Triangle Congruence Proof",
                              "Heron's Formula Practice", "Polynomial Factor Activity"],
    ("9", "Hindi"):          ["काव्य विश्लेषण प्रतियोगिता", "पत्रकारिता लेखन",
                              "गद्यांश बोध", "व्याकरण प्रश्नोत्तरी"],
    ("9", "English"):        ["Report Writing Activity", "Novel Discussion Circle",
                              "Grammar Olympics", "Creative Writing Workshop"],
    ("9", "Social Science"): ["French Revolution Timeline", "Electoral Process Role Play",
                              "Drainage Map of India", "River Basin Mapping"],
    ("9", "General"):        ["Motion Graph Drawing", "Coordinate Geometry Plotting",
                              "French Revolution Timeline", "Report Writing Activity"],

    # ── Class 10 ─────────────────────────────────────────────────────────────
    ("10", "Science"):       ["Chemical Equation Balancing", "Acid Base Titration Demo",
                              "Electric Circuit Calculation", "DNA Model Making"],
    ("10", "Mathematics"):   ["Quadratic Equation Word Problems", "Trigonometry Heights Activity",
                              "Probability Coin Toss Experiment", "Circle Theorem Proof"],
    ("10", "Hindi"):         ["काव्य सौंदर्य विश्लेषण", "पद पाठ और अर्थ",
                              "संदेश लेखन अभ्यास", "साहित्यिक वाद-विवाद"],
    ("10", "English"):       ["Speech Writing & Delivery", "Formal Letter Competition",
                              "Literature Discussion Circle", "Grammar Rapid Fire Round"],
    ("10", "Social Science"):["Federalism Case Study", "Economic Data Analysis",
                              "Consumer Rights Role Play", "Resource Map of India"],
    ("10", "General"):       ["Chemical Equation Balancing", "Quadratic Equation Problems",
                              "Consumer Rights Role Play", "Speech Writing Activity"],

    # ── Class 11 ─────────────────────────────────────────────────────────────
    ("11", "Physics"):       ["Motion Graph Analysis", "Newton's Laws Demo with Objects",
                              "Thermodynamics Real-life Examples", "Wave Interference Demonstration"],
    ("11", "Chemistry"):     ["Atom Model Making (Bohr)", "Bond Angle Shape Activity",
                              "Acid Base Equilibrium Test", "Organic Compound Ball & Stick Models"],
    ("11", "Biology"):       ["Cell Diagram Detailed Labeling", "Mitosis Role Play Activity",
                              "Photosynthesis Experiment (leaf disc)", "Neural Pathway Mapping"],
    ("11", "Mathematics"):   ["Trigonometry Real-life Application", "Set Venn Diagram Activity",
                              "Complex Number on Number Plane", "Sequence & Series Pattern Finding"],
    ("11", "Economics"):     ["Demand Supply Curve Drawing", "Market Form Discussion & Role Play",
                              "National Income Calculation Activity", "Budget Analysis Exercise"],
    ("11", "Computer Science"):["Python Hello World & Variables", "Simple Calculator Program",
                               "List Operations Practice", "File Read Write Activity"],
    ("11", "Business Studies"):["Business Type Comparison Chart", "Corporate Social Responsibility Case Study",
                                "E-Commerce vs Traditional Business Debate", "Business Plan Presentation"],
    ("11", "History"):       ["Ancient Society Timeline Making", "Mesopotamia Civilisation Map",
                              "Medieval Europe Three Orders Role Play", "Colonial Impact Discussion"],
    ("11", "Political Science"):["Constitution Making Role Play", "Rights & Duties Discussion",
                                 "Election Process Simulation", "Landmark Judgements Case Study"],
    ("11", "English"):       ["Photo Essay Writing", "Group Discussion: Human Spirit",
                              "Report Writing Practice", "Poetry Analysis Circle"],
    ("11", "Hindi"):         ["गद्य पाठ विश्लेषण", "पद्य भाव व्याख्या",
                              "संधि-समास अभ्यास", "वाद-विवाद प्रतियोगिता"],
    ("11", "Social Science"):["India Physical Map Labelling", "Climate Data Analysis",
                              "Pre & Post Independence Economy Comparison", "Human Development Index Activity"],
    ("11", "General"):       ["Newton's Laws Demonstration", "Demand Supply Curve Drawing",
                              "Cell Diagram Labeling", "Python Calculator Program"],

    # ── Class 12 ─────────────────────────────────────────────────────────────
    ("12", "Physics"):       ["Electric Field Line Drawing Activity", "Circuit Building & Verification",
                              "Ray Diagram for Lenses & Mirrors", "Photoelectric Effect Discussion"],
    ("12", "Chemistry"):     ["Crystal Structure Model Making", "Electrochemical Cell Demo",
                              "Reaction Rate & Concentration Experiment", "Coordination Compound Models"],
    ("12", "Biology"):       ["Genetics Dihybrid Cross Activity", "DNA Extraction Demo",
                              "Ecosystem Food Web Making", "Biotechnology Case Study Discussion"],
    ("12", "Mathematics"):   ["Matrix Operations Practice Sheet", "Derivative Application: Maxima Minima",
                              "Probability Experiment with Cards/Dice", "Integration by Substitution Problems"],
    ("12", "Economics"):     ["GDP Calculation Activity", "Budget Deficit Analysis Exercise",
                              "Trade Balance Case Study", "India vs China Development Comparison"],
    ("12", "Computer Science"):["SQL Query Practice on Sample DB", "Stack Implementation in Python",
                                "Network Topology Drawing", "Cybersecurity Threats Case Study"],
    ("12", "Business Studies"):["Management Principles Case Study (Fayol)", "Marketing Mix (4Ps) Analysis",
                                "Consumer Protection Act Role Play", "Business Plan Pitching Activity"],
    ("12", "History"):       ["Harappan Civilisation Artefact Analysis", "1857 Revolt Timeline",
                              "Constitution Making Process Discussion", "Bhakti-Sufi Movement Comparison"],
    ("12", "Political Science"):["Cold War Timeline Activity", "UN Role Play Simulation",
                                 "Indian Social Movement Debate", "Electoral Politics Case Study"],
    ("12", "English"):       ["Short Story Analysis Circle", "Creative Writing Workshop",
                              "Formal Letter & Report Competition", "Poetry Recitation & Interpretation"],
    ("12", "Hindi"):         ["कहानी की समीक्षा", "काव्यांश व्याख्या",
                              "साहित्यिक वाद-विवाद", "लेखन कौशल अभ्यास"],
    ("12", "Social Science"):["Globalisation Debate", "Agrarian Change Case Study",
                              "Environment & Society Discussion", "Social Movement Mapping Activity"],
    ("12", "General"):       ["Electric Circuit Building", "Genetics Cross Activity",
                              "Derivative Application Problems", "SQL Query Practice"],
}

# ── Fallback ──────────────────────────────────────────────────────────────────
_CONCEPT_FALLBACK    = ["Photosynthesis", "Newton's Laws", "Water Cycle", "Fractions", "Human Heart", "Electricity"]
_CONCEPT_FALLBACK_HI = ["प्रकाश संश्लेषण", "न्यूटन के नियम", "जल चक्र", "भिन्न", "मानव हृदय", "विद्युत"]
_ACTIVITY_FALLBACK    = ["Water Conservation Activity", "Parts of a Plant", "Fractions with Paper", "Solar System Model"]
_ACTIVITY_FALLBACK_HI = ["जल संरक्षण गतिविधि", "पौधे के भाग", "कागज़ से भिन्न", "सौर मंडल मॉडल"]

# ── Hindi concept/quiz topic names ────────────────────────────────────────────
# English subject chips stay in English; all others get Hindi equivalents.
_CONCEPT_TOPICS_HI = {
    ("LKG", "General"):       ["रंग और आकार", "गिनती 1–10", "हमारे जानवर", "फल और सब्जियाँ", "मेरे अंग", "मेरा परिवार"],
    ("UKG", "General"):       ["वर्णमाला अ–ज्ञ", "गिनती 1–50", "सप्ताह के दिन", "ऋतुएँ और मौसम", "यातायात के साधन", "पौधे और पेड़"],

    ("1", "Science"):         ["मेरा परिवार", "पौधे के भाग", "जानवर और उनके घर", "हमारा भोजन", "पानी का उपयोग", "हमारी पाँच इंद्रियाँ"],
    ("1", "Mathematics"):     ["1–100 तक संख्याएँ", "जोड़", "घटाव", "मूल आकार", "सरल माप", "पैटर्न"],
    ("1", "Hindi"):           ["वर्णमाला – स्वर", "वर्णमाला – व्यंजन", "सरल शब्द", "मेरा परिचय", "रंग और आकार", "कविता पाठ"],
    ("1", "English"):         ["Alphabet A–Z", "Simple CVC Words", "My Body", "Colours & Numbers", "Nursery Rhymes", "Simple Sentences"],
    ("1", "General"):         ["मेरा परिवार", "1–100 संख्याएँ", "वर्णमाला", "जानवर और घर", "रंग और आकार", "हमारा भोजन"],

    ("2", "Science"):         ["हमारे पौधे", "पालतू और जंगली जानवर", "भोजन और पोषण", "पानी का उपयोग", "वायु का महत्व", "ऋतुएँ और मौसम"],
    ("2", "Mathematics"):     ["1000 तक संख्याएँ", "हासिल के साथ जोड़", "उधार से घटाव", "गुणा सारणी", "सरल भिन्न", "लम्बाई और वजन"],
    ("2", "Hindi"):           ["संज्ञा", "सर्वनाम", "सरल क्रिया", "सरल वाक्य", "छोटी कहानी", "पत्र लेखन"],
    ("2", "English"):         ["Nouns", "Pronouns", "Simple Verbs", "Simple Sentences", "Story Reading", "Rhymes & Poems"],
    ("2", "General"):         ["हमारे पौधे", "1000 तक संख्याएँ", "संज्ञा", "पालतू और जंगली जानवर", "गुणा सारणी", "ऋतुएँ"],

    ("3", "Science"):         ["पौधे के भाग", "जानवरों के आवास", "हमारा भोजन और स्वास्थ्य", "पानी के स्रोत", "वायु और प्रदूषण", "पृथ्वी और आकाश"],
    ("3", "Mathematics"):     ["4 अंकों की संख्याएँ", "गुणा", "भाग की मूल बातें", "सरल भिन्न", "परिमाप", "समय और कैलेंडर"],
    ("3", "Hindi"):           ["संज्ञा के भेद", "विशेषण", "क्रिया के प्रकार", "विलोम शब्द", "पर्यायवाची शब्द", "अनुच्छेद लेखन"],
    ("3", "English"):         ["Parts of Speech", "Simple Tenses", "Articles", "Comprehension", "Letter Writing", "Vocabulary Building"],
    ("3", "Social Science"):  ["हमारा पड़ोस", "सामुदायिक सहायक", "नक्शे और दिशाएँ", "हमारा राज्य", "यातायात और संचार", "भारत के त्योहार"],
    ("3", "General"):         ["पौधे के भाग", "4 अंकों की संख्याएँ", "संज्ञा के भेद", "जानवरों के आवास", "गुणा", "हमारा पड़ोस"],

    ("4", "Science"):         ["पौधे के भाग", "हमारा भोजन", "जानवर और उनके आवास", "वायु और जल", "सरल यंत्र", "हमारा पर्यावरण"],
    ("4", "Mathematics"):     ["जोड़ और घटाव", "गुणा सारणी", "भाग की मूल बातें", "सरल भिन्न", "2D आकार", "माप"],
    ("4", "Hindi"):           ["वर्णमाला", "संज्ञा और सर्वनाम", "विलोम शब्द", "पर्यायवाची", "वाक्य रचना", "कहानी लेखन"],
    ("4", "English"):         ["Nouns & Pronouns", "Simple Sentences", "Action Words (Verbs)", "Adjectives", "Story Reading", "Rhymes & Poems"],
    ("4", "Social Science"):  ["हमारा परिवार और समाज", "हमारा पड़ोस", "नक्शे और दिशाएँ", "यातायात के साधन", "हमारा देश भारत", "भारत के त्योहार"],
    ("4", "General"):         ["पौधे के भाग", "जोड़ और घटाव", "हमारा परिवार", "संज्ञा और सर्वनाम", "जानवर और आवास", "नक्शे और दिशाएँ"],

    ("5", "Science"):         ["प्रकाश संश्लेषण", "खाद्य श्रृंखला", "सौर मंडल", "मानव शरीर", "पानी के गुण", "सरल यंत्र"],
    ("5", "Mathematics"):     ["बड़ी संख्याएँ", "भिन्न", "दशमलव", "क्षेत्रफल और परिमाप", "कोण", "रोमन संख्याएँ"],
    ("5", "Hindi"):           ["संज्ञा", "विशेषण", "क्रिया", "पत्र लेखन", "मुहावरे", "निबंध लेखन"],
    ("5", "English"):         ["Tenses", "Articles (a an the)", "Prepositions", "Comprehension Skills", "Letter Writing", "Conjunctions"],
    ("5", "Social Science"):  ["विश्व में भारत", "स्वतंत्रता संग्राम", "प्राकृतिक संसाधन", "भारत की जलवायु", "मिट्टी और कृषि", "राज्य और राजधानी"],
    ("5", "General"):         ["प्रकाश संश्लेषण", "भिन्न", "विश्व में भारत", "सौर मंडल", "खाद्य श्रृंखला", "कोण"],

    ("6", "Science"):         ["प्रकाश संश्लेषण", "खाद्य श्रृंखला और जाल", "गति और मापन", "प्रकाश और छाया", "जल चक्र", "भोजन के घटक"],
    ("6", "Mathematics"):     ["संख्याओं की जानकारी", "भिन्न और दशमलव", "बीजगणित परिचय", "रेखाएँ और कोण", "पूर्णांक", "अनुपात और समानुपात"],
    ("6", "Hindi"):           ["संज्ञा के भेद", "विशेषण", "क्रिया के भेद", "मुहावरे", "पत्र लेखन", "अनुच्छेद लेखन"],
    ("6", "English"):         ["Parts of Speech", "Simple Present Tense", "Reading Comprehension", "Letter Writing", "Vocabulary Building", "Punctuation"],
    ("6", "Social Science"):  ["सिंधु घाटी सभ्यता", "ग्लोब और अक्षांश", "भारत की विविधता", "पंचायती राज", "ग्रामीण और शहरी आजीविका", "पृथ्वी और सौर मंडल"],
    ("6", "General"):         ["प्रकाश संश्लेषण", "संख्याओं की जानकारी", "सिंधु घाटी सभ्यता", "संज्ञा के भेद", "जल चक्र", "ग्लोब और अक्षांश"],

    ("7", "Science"):         ["पौधों में पोषण", "ऊष्मा और तापमान", "गति और समय", "विद्युत धारा", "अम्ल क्षार और लवण", "मौसम जलवायु और अनुकूलन"],
    ("7", "Mathematics"):     ["पूर्णांक", "भिन्न और दशमलव", "सरल समीकरण", "रेखाएँ और कोण", "अनुपात और समानुपात", "प्रतिशत"],
    ("7", "Hindi"):           ["संधि", "समास", "काल के भेद", "वाच्य", "अलंकार", "निबंध लेखन"],
    ("7", "English"):         ["Passive Voice", "Reported Speech", "Degrees of Adjective", "Reading Comprehension", "Essay Writing", "Phrasal Verbs"],
    ("7", "Social Science"):  ["मध्यकालीन राज्य", "दिल्ली सल्तनत", "मुगल साम्राज्य", "जनजातियाँ और वन", "जल संसाधन", "लोकतांत्रिक सरकार"],
    ("7", "General"):         ["पौधों में पोषण", "सरल समीकरण", "मुगल साम्राज्य", "ऊष्मा और तापमान", "प्रतिशत", "विद्युत धारा"],

    ("8", "Science"):         ["फसल उत्पादन", "सूक्ष्मजीव", "धातु और अधातु", "कोशिका संरचना", "दहन और ज्वाला", "घर्षण"],
    ("8", "Mathematics"):     ["परिमेय संख्याएँ", "एक चर में रैखिक समीकरण", "वर्ग और वर्गमूल", "क्षेत्रमिति", "चतुर्भुज", "आँकड़ा प्रबंधन"],
    ("8", "Hindi"):           ["संधि विच्छेद", "समास", "रस और छंद", "अपठित गद्यांश", "पत्र लेखन", "व्याकरण अभ्यास"],
    ("8", "English"):         ["Modals (can could may)", "Compound & Complex Sentences", "Idioms & Phrases", "Formal Letter Writing", "Active & Passive Voice", "Reported Speech"],
    ("8", "Social Science"):  ["भारत में उपनिवेशवाद", "उद्योग और व्यापार", "प्राकृतिक संसाधन", "भारतीय संविधान", "न्यायपालिका", "सामाजिक मुद्दे"],
    ("8", "General"):         ["सूक्ष्मजीव", "रैखिक समीकरण", "भारतीय संविधान", "कोशिका संरचना", "वर्गमूल", "धातु और अधातु"],

    ("9", "Science"):         ["हमारे आस-पास के पदार्थ", "गति (चाल और वेग)", "बल और न्यूटन के नियम", "गुरुत्वाकर्षण", "कार्य ऊर्जा और शक्ति", "ध्वनि तरंगें"],
    ("9", "Mathematics"):     ["संख्या पद्धति (अपरिमेय संख्याएँ)", "बहुपद", "निर्देशांक ज्यामिति", "त्रिभुज की सर्वांगसमता", "वृत्त और जीवाएँ", "हीरोन का सूत्र"],
    ("9", "Hindi"):           ["क्षितिज काव्य खंड", "गद्य साहित्य", "अपठित बोध", "व्याकरण – काल", "पत्र और निबंध", "संचार माध्यम"],
    ("9", "English"):         ["Tenses Review", "The Fun They Had", "The Sound of Music", "Modals & Conditionals", "Reported Speech", "Writing a Report"],
    ("9", "Social Science"):  ["फ्रांसीसी क्रांति", "समाजवाद और रूसी क्रांति", "नाज़ीवाद और हिटलर", "वन समाज और उपनिवेशवाद", "चुनावी राजनीति", "भारत का अपवाह तंत्र"],
    ("9", "General"):         ["न्यूटन के गति के नियम", "बहुपद", "फ्रांसीसी क्रांति", "हमारे आस-पास पदार्थ", "निर्देशांक ज्यामिति", "गुरुत्वाकर्षण"],

    ("10", "Science"):        ["रासायनिक अभिक्रियाएँ और समीकरण", "अम्ल क्षार और लवण", "धातु और अधातु", "जीवन प्रक्रियाएँ", "विद्युत और परिपथ", "आनुवंशिकता और विकास"],
    ("10", "Mathematics"):    ["वास्तविक संख्याएँ", "बहुपद", "द्विघात समीकरण", "त्रिकोणमिति", "वृत्त और स्पर्श रेखाएँ", "प्रायिकता"],
    ("10", "Hindi"):          ["सूरदास के पद", "तुलसीदास – रामचरितमानस", "मीराबाई", "काव्य सौंदर्य", "वितान गद्य", "संदेश लेखन"],
    ("10", "English"):        ["Nelson Mandela", "From the Diary of Anne Frank", "Letter Writing (Formal)", "The Midnight Visitor", "Grammar: Determiners", "Speech Writing"],
    ("10", "Social Science"): ["भारत में राष्ट्रवाद", "संघवाद", "लोकतंत्र और विविधता", "आर्थिक विकास", "उपभोक्ता अधिकार", "संसाधन और विकास"],
    ("10", "General"):        ["रासायनिक अभिक्रियाएँ", "वास्तविक संख्याएँ", "भारत में राष्ट्रवाद", "जीवन प्रक्रियाएँ", "द्विघात समीकरण", "प्रायिकता"],

    ("11", "Physics"):        ["सरल रेखा में गति", "न्यूटन के गति के नियम", "कार्य ऊर्जा और शक्ति", "गुरुत्वाकर्षण", "ऊष्मागतिकी", "तरंगें और ध्वनि"],
    ("11", "Chemistry"):      ["परमाणु की संरचना", "रासायनिक बंधन और आणविक संरचना", "ऊष्मागतिकी", "रासायनिक साम्यावस्था", "ऑक्सीकरण-अपचयन", "हाइड्रोकार्बन"],
    ("11", "Biology"):        ["कोशिका: जीवन की इकाई", "जैव अणु", "कोशिका विभाजन (माइटोसिस और मेयोसिस)", "उच्च पादपों में प्रकाश संश्लेषण", "पादपों में श्वसन", "तंत्रिका नियंत्रण"],
    ("11", "Mathematics"):    ["समुच्चय और संबंध", "त्रिकोणमितीय फलन", "सम्मिश्र संख्याएँ", "अनुक्रम और श्रेणी", "सीमाएँ और अवकलज", "क्रमचय और संचय"],
    ("11", "Economics"):      ["सूक्ष्मअर्थशास्त्र परिचय", "उपभोक्ता संतुलन और माँग", "उत्पादन और लागत सिद्धांत", "बाज़ार के रूप", "राष्ट्रीय आय परिचय", "मुद्रा और बैंकिंग"],
    ("11", "Computer Science"):["Python की मूल बातें", "डेटा प्रकार और चर", "नियंत्रण संरचनाएँ", "Python में फलन", "सूची, टपल और शब्दकोश", "फ़ाइल प्रबंधन"],
    ("11", "Business Studies"):["व्यवसाय की प्रकृति और महत्व", "व्यावसायिक संगठन के रूप", "निजी-सार्वजनिक उद्यम", "व्यावसायिक सेवाएँ", "व्यापार के नए तरीके", "व्यवसाय की सामाजिक जिम्मेदारी"],
    ("11", "History"):        ["प्रारंभिक समाज", "लेखन और नगर जीवन (मेसोपोटामिया)", "घुमंतू साम्राज्य", "तीन वर्ग (मध्यकालीन यूरोप)", "बदलती सांस्कृतिक परंपराएँ", "मूल निवासियों का विस्थापन"],
    ("11", "Political Science"):["संविधान: क्यों और कैसे", "भारतीय संविधान में अधिकार", "चुनाव और प्रतिनिधित्व", "कार्यपालिका", "विधायिका (संसद)", "न्यायपालिका"],
    ("11", "English"):        ["The Portrait of a Lady", "A Photograph", "We're Not Afraid to Die", "Discovering Tut", "Voice of the Rain", "Writing Skills: Report"],
    ("11", "Hindi"):          ["नमक का दारोगा", "मियाँ नसीरुद्दीन", "आलो-आँधारि", "बात सीधी थी पर", "पद्य – कबीर के पद", "व्याकरण – संधि समास"],
    ("11", "Social Science"):  ["भारत की भौतिक विशेषताएँ", "भारत की जलवायु", "प्राकृतिक वनस्पति", "स्वतंत्रता पर भारतीय अर्थव्यवस्था", "उदारीकरण और वैश्वीकरण", "मानव विकास"],
    ("11", "General"):        ["न्यूटन के गति के नियम", "रासायनिक बंधन", "कोशिका विज्ञान", "त्रिकोणमितीय फलन", "उपभोक्ता सिद्धांत", "Python की मूल बातें"],

    ("12", "Physics"):        ["आवेश और क्षेत्र (कूलॉम नियम)", "विद्युत धारा (ओम नियम)", "धारा के चुंबकीय प्रभाव", "विद्युतचुंबकीय प्रेरण", "किरण प्रकाशिकी", "विकिरण और द्रव्य की द्वैत प्रकृति"],
    ("12", "Chemistry"):      ["ठोस अवस्था", "विलयन और अणुसंख्य गुण", "वैद्युत रसायन", "रासायनिक बलगतिकी", "उपसहसंयोजन यौगिक", "जैव अणु और बहुलक"],
    ("12", "Biology"):        ["पुष्पी पादपों में लैंगिक प्रजनन", "मानव प्रजनन", "आनुवंशिकता के सिद्धांत (मेंडल)", "आनुवंशिकता का आणविक आधार (DNA)", "जैव प्रौद्योगिकी", "पारिस्थितिकी तंत्र और जैव विविधता"],
    ("12", "Mathematics"):    ["संबंध और फलन", "प्रतिलोम त्रिकोणमितीय फलन", "आव्यूह और सारणिक", "सांतत्य और अवकलनीयता", "अवकलज के अनुप्रयोग", "प्रायिकता (बेयस प्रमेय)"],
    ("12", "Economics"):      ["राष्ट्रीय आय लेखांकन", "मुद्रा आपूर्ति और बैंकिंग", "आय निर्धारण (AD-AS मॉडल)", "सरकारी बजट और राजकोषीय नीति", "भुगतान संतुलन", "भारत-चीन-पाकिस्तान विकास तुलना"],
    ("12", "Computer Science"):["Python: OOP अवधारणाएँ", "स्टैक और क्यू (DSA)", "लिंक्ड लिस्ट", "डेटाबेस और SQL", "कंप्यूटर नेटवर्क और प्रोटोकॉल", "साइबर सुरक्षा"],
    ("12", "Business Studies"):["प्रबंधन की प्रकृति और महत्व", "प्रबंधन के सिद्धांत (फेयोल-टेलर)", "व्यावसायिक वातावरण", "नियोजन और निर्णय लेना", "विपणन प्रबंधन (4P)", "उपभोक्ता संरक्षण अधिनियम"],
    ("12", "History"):        ["ईंटें मनके और हड्डियाँ (हड़प्पा)", "राजा किसान और नगर", "भक्ति सूफी परंपराएँ", "विद्रोही और राज (1857)", "संविधान का निर्माण", "रिश्ते जाति और वर्ग"],
    ("12", "Political Science"):["शीत युद्ध का दौर", "द्विध्रुवीयता का अंत", "अमेरिकी वर्चस्व", "सत्ता के वैकल्पिक केंद्र (EU चीन)", "भारत में जन आंदोलन", "नए सामाजिक आंदोलन"],
    ("12", "English"):        ["The Last Lesson", "Lost Spring", "Deep Water", "The Rattrap", "My Mother at Sixty-six", "Going Places"],
    ("12", "Hindi"):          ["भक्तिन", "बाज़ार दर्शन", "काले मेघा पानी दे", "पहलवान की ढोलक", "सिल्वर वेडिंग", "जूझ"],
    ("12", "Social Science"):  ["वैश्वीकरण और उसके प्रभाव", "सामाजिक आंदोलन", "सांस्कृतिक परिवर्तन", "बाज़ार एक सामाजिक संस्था", "पर्यावरण और समाज", "कृषि समाज और परिवर्तन"],
    ("12", "General"):        ["आवेश और क्षेत्र", "वैद्युत रसायन", "मेंडल के आनुवंशिकता के नियम", "अवकलज के अनुप्रयोग", "राष्ट्रीय आय लेखांकन", "SQL डेटाबेस"],
}

# ── Hindi activity topic names ─────────────────────────────────────────────────
_ACTIVITY_TOPICS_HI = {
    ("LKG", "General"):       ["रंग छँटाई खेल", "आकार पहचान गतिविधि", "वस्तुओं से गिनती", "जानवर आवाज़ खेल"],
    ("UKG", "General"):       ["वर्णमाला लेखन अभ्यास", "संख्या क्रम खेल", "ऋतु चित्र गतिविधि", "यातायात छँटाई खेल"],
    ("1", "Science"):         ["बीज बोने का अवलोकन", "पाँच इंद्रियाँ गतिविधि", "जानवर मिलान खेल", "पानी उपयोग प्रयोग"],
    ("1", "Mathematics"):     ["संख्या रेखा चलो", "कक्षा में आकार खोजो", "वस्तुओं की गिनती खेल", "पैटर्न निर्माण"],
    ("1", "Hindi"):           ["वर्णमाला गायन", "शब्द बनाओ खेल", "कविता पाठ", "चित्र देखो बताओ"],
    ("1", "English"):         ["Alphabet Song & Writing", "Word Building with Cards", "Story Telling Circle", "Poem Recitation"],
    ("1", "General"):         ["बीज बोने का अवलोकन", "संख्या रेखा चलो", "आकार खोजो", "पाँच इंद्रियाँ गतिविधि"],
    ("2", "Science"):         ["भोजन समूह छँटाई", "जल चक्र चित्र", "जानवर आवास मिलान", "गुब्बारे से वायु प्रयोग"],
    ("2", "Mathematics"):     ["छोड़ गिनती खेल", "पत्थरों से जोड़", "आकार की भिन्न गतिविधि", "वजन माप गतिविधि"],
    ("2", "Hindi"):           ["संज्ञा शब्द संग्रह", "वाक्य निर्माण खेल", "कहानी सुनाओ", "कविता पाठ प्रतियोगिता"],
    ("2", "English"):         ["Noun Hunt in Classroom", "Verb Action Game", "Story Sequencing Cards", "Simple Sentence Making"],
    ("2", "General"):         ["भोजन समूह छँटाई", "छोड़ गिनती खेल", "संज्ञा शब्द खोज", "जल चक्र चित्र"],
    ("3", "Science"):         ["पौधे के भाग लेबलिंग", "आवास डायोरामा निर्माण", "जल शुद्धिकरण प्रदर्शन", "मौसम अवलोकन चार्ट"],
    ("3", "Mathematics"):     ["गुणा सारणी दौड़", "कागज़ से भिन्न पिज़्ज़ा", "परिमाप माप", "कैलेंडर गतिविधि"],
    ("3", "Hindi"):           ["विलोम शब्द खेल", "पर्यायवाची मिलाओ", "अनुच्छेद लेखन", "कहानी नाटक"],
    ("3", "English"):         ["Tense Changing Game", "Article Fill-in Activity", "Comprehension Race", "Letter Writing Practice"],
    ("3", "Social Science"):  ["पड़ोस का नक्शा बनाओ", "सामुदायिक सहायक भूमिका नाटक", "त्योहार कोलाज", "यातायात छँटाई"],
    ("3", "General"):         ["पौधे के भाग लेबलिंग", "गुणा सारणी दौड़", "पड़ोस का नक्शा", "विलोम शब्द खेल"],
    ("4", "Science"):         ["पत्ती रगड़ गतिविधि", "बीज बोने का प्रयोग", "जल वाष्पीकरण प्रदर्शन", "जानवर छँटाई खेल"],
    ("4", "Mathematics"):     ["पत्थरों से छोड़ गिनती", "कक्षा में आकार खोज", "कागज़ से भिन्न पिज़्ज़ा", "रूलर से माप"],
    ("4", "Hindi"):           ["कविता पाठ प्रतियोगिता", "शब्द निर्माण खेल", "कहानी सुनाओ", "वर्णमाला गेम"],
    ("4", "English"):         ["Story Telling Circle", "Word Building Game", "Sentence Making Activity", "Poem Recitation"],
    ("4", "Social Science"):  ["पड़ोस का नक्शा बनाओ", "परिवार वृक्ष गतिविधि", "यातायात छँटाई खेल", "त्योहार कोलाज"],
    ("4", "General"):         ["बीज बोने का प्रयोग", "कक्षा में आकार खोज", "पड़ोस का नक्शा", "कहानी सुनाओ"],
    ("5", "Science"):         ["खाद्य श्रृंखला चित्र गतिविधि", "सौर मंडल मॉडल", "थैले में जल चक्र", "सरल यंत्र खोज"],
    ("5", "Mathematics"):     ["कागज़ से भिन्न पिज़्ज़ा", "ग्राफ पेपर से क्षेत्रफल", "दशमलव खरीदारी खेल", "कोण माप"],
    ("5", "Hindi"):           ["पत्र लेखन अभ्यास", "मुहावरे पर नाटक", "कविता रचना", "समाचार वाचन"],
    ("5", "English"):         ["Letter Writing Practice", "Tense Changing Game", "Story Sequencing", "Debate Activity"],
    ("5", "Social Science"):  ["भारत का नक्शा लेबलिंग", "स्वतंत्रता सेनानी भूमिका नाटक", "जलवायु चार्ट", "राज्य-राजधानी प्रश्नोत्तरी"],
    ("5", "General"):         ["खाद्य श्रृंखला चित्र", "कागज़ से भिन्न पिज़्ज़ा", "भारत का नक्शा", "पत्र लेखन"],
    ("6", "Science"):         ["प्रकाश संश्लेषण चित्र गतिविधि", "खाद्य जाल निर्माण", "छाया लंबाई प्रयोग", "जल शुद्धिकरण प्रदर्शन"],
    ("6", "Mathematics"):     ["पूर्णांक संख्या रेखा खेल", "भिन्न पट्टी गतिविधि", "ज्यामिति आकार चित्रण", "डेटा संग्रह और बार ग्राफ"],
    ("6", "Hindi"):           ["मुहावरे पर नाटक", "पत्र लेखन प्रतियोगिता", "कविता पाठ", "संज्ञा शब्द संग्रह"],
    ("6", "English"):         ["Parts of Speech Sorting", "Newspaper Reading Activity", "Debate on a Topic", "Creative Story Writing"],
    ("6", "Social Science"):  ["सिंधु घाटी मॉडल निर्माण", "ग्लोब अवलोकन", "पंचायत भूमिका नाटक", "भारत का नक्शा चित्रण"],
    ("6", "General"):         ["प्रकाश संश्लेषण चित्र", "पूर्णांक संख्या रेखा", "ग्लोब अवलोकन", "मुहावरे पर नाटक"],
    ("7", "Science"):         ["अम्ल-क्षार सूचक परीक्षण", "पौधों में पोषण चार्ट", "विद्युत परिपथ निर्माण", "ऊष्मा चालन प्रयोग"],
    ("7", "Mathematics"):     ["समीकरण सुलझाने की दौड़", "प्रतिशत छूट गतिविधि", "कोण द्विभाजक चित्रण", "अनुपात रेसिपी गतिविधि"],
    ("7", "Hindi"):           ["समास पहचान खेल", "काल परिवर्तन अभ्यास", "वाद-विवाद प्रतियोगिता", "अलंकार पहचान"],
    ("7", "English"):         ["Passive Voice Conversion", "Group Debate Activity", "Phrasal Verb Matching", "Role Play: Reported Speech"],
    ("7", "Social Science"):  ["मुगल साम्राज्य समयरेखा", "जल संरक्षण पोस्टर", "लोकतांत्रिक प्रक्रिया भूमिका नाटक", "मध्यकालीन व्यापार मार्ग नक्शा"],
    ("7", "General"):         ["अम्ल-क्षार सूचक परीक्षण", "प्रतिशत छूट गतिविधि", "मुगल साम्राज्य समयरेखा", "वाद-विवाद"],
    ("8", "Science"):         ["फसल चक्र चित्र", "सूक्ष्मजीव अवलोकन", "धातु अभिक्रिया श्रेणी", "कोशिका विभाजन मॉडल"],
    ("8", "Mathematics"):     ["परिमेय संख्या रेखा", "कक्षा की क्षेत्रमिति", "डेटा प्रबंधन सर्वेक्षण", "वर्गमूल अनुमान"],
    ("8", "Hindi"):           ["अपठित गद्यांश विश्लेषण", "समास रचना खेल", "रस पहचान प्रतियोगिता", "पत्र लेखन"],
    ("8", "English"):         ["Formal Letter Writing", "Idiom Illustration Activity", "Active Passive Game", "Group Discussion"],
    ("8", "Social Science"):  ["संविधान अध्ययन मंडली", "उद्योग स्थान नक्शा", "सामाजिक मुद्दे वाद-विवाद", "उपनिवेशी इतिहास समयरेखा"],
    ("8", "General"):         ["सूक्ष्मजीव चार्ट", "कक्षा की क्षेत्रमिति", "संविधान अध्ययन", "औपचारिक पत्र लेखन"],
    ("9", "Science"):         ["गति ग्राफ चित्रण", "न्यूटन के नियम प्रदर्शन", "ध्वनि तरंग प्रयोग", "गुरुत्वाकर्षण गणना"],
    ("9", "Mathematics"):     ["निर्देशांक ज्यामिति आलेखन", "त्रिभुज सर्वांगसमता प्रमाण", "हीरोन सूत्र अभ्यास", "बहुपद गुणनखंड"],
    ("9", "Hindi"):           ["काव्य विश्लेषण प्रतियोगिता", "पत्रकारिता लेखन", "गद्यांश बोध", "व्याकरण प्रश्नोत्तरी"],
    ("9", "English"):         ["Report Writing Activity", "Novel Discussion Circle", "Grammar Olympics", "Creative Writing Workshop"],
    ("9", "Social Science"):  ["फ्रांसीसी क्रांति समयरेखा", "चुनाव प्रक्रिया भूमिका नाटक", "भारत का अपवाह नक्शा", "नदी बेसिन मानचित्रण"],
    ("9", "General"):         ["गति ग्राफ चित्रण", "निर्देशांक आलेखन", "फ्रांसीसी क्रांति समयरेखा", "रिपोर्ट लेखन"],
    ("10", "Science"):        ["रासायनिक समीकरण संतुलन", "अम्ल-क्षार अनुमापन प्रदर्शन", "विद्युत परिपथ गणना", "DNA मॉडल निर्माण"],
    ("10", "Mathematics"):    ["द्विघात समीकरण के शब्द प्रश्न", "त्रिकोणमिति ऊँचाई गतिविधि", "प्रायिकता सिक्का प्रयोग", "वृत्त प्रमेय प्रमाण"],
    ("10", "Hindi"):          ["काव्य सौंदर्य विश्लेषण", "पद पाठ और अर्थ", "संदेश लेखन अभ्यास", "साहित्यिक वाद-विवाद"],
    ("10", "English"):        ["Speech Writing & Delivery", "Formal Letter Competition", "Literature Discussion Circle", "Grammar Rapid Fire Round"],
    ("10", "Social Science"): ["संघवाद केस स्टडी", "आर्थिक डेटा विश्लेषण", "उपभोक्ता अधिकार भूमिका नाटक", "भारत का संसाधन नक्शा"],
    ("10", "General"):        ["रासायनिक समीकरण संतुलन", "द्विघात समीकरण प्रश्न", "उपभोक्ता अधिकार नाटक", "भाषण लेखन"],
    ("11", "Physics"):        ["गति ग्राफ विश्लेषण", "न्यूटन नियम प्रदर्शन", "ऊष्मागतिकी वास्तविक उदाहरण", "तरंग व्यतिकरण प्रदर्शन"],
    ("11", "Chemistry"):      ["परमाणु मॉडल निर्माण (बोर)", "बंध कोण आकार गतिविधि", "अम्ल-क्षार साम्यावस्था परीक्षण", "कार्बनिक यौगिक मॉडल"],
    ("11", "Biology"):        ["कोशिका चित्र विस्तृत लेबलिंग", "माइटोसिस भूमिका नाटक", "प्रकाश संश्लेषण प्रयोग", "तंत्रिका पथ मानचित्रण"],
    ("11", "Mathematics"):    ["त्रिकोणमिति व्यावहारिक प्रयोग", "समुच्चय वेन आरेख", "सम्मिश्र संख्या तल", "अनुक्रम-श्रेणी पैटर्न"],
    ("11", "Economics"):      ["माँग-आपूर्ति वक्र चित्रण", "बाज़ार रूप चर्चा और नाटक", "राष्ट्रीय आय गणना", "बजट विश्लेषण"],
    ("11", "Computer Science"):["Python हेलो वर्ल्ड", "सरल कैलकुलेटर प्रोग्राम", "सूची संचालन अभ्यास", "फ़ाइल पढ़ना-लिखना"],
    ("11", "Business Studies"):["व्यवसाय प्रकार तुलना चार्ट", "CSR केस स्टडी", "ई-कॉमर्स vs परंपरागत बहस", "व्यवसाय योजना प्रस्तुति"],
    ("11", "History"):        ["प्राचीन समाज समयरेखा", "मेसोपोटामिया सभ्यता नक्शा", "मध्यकालीन यूरोप भूमिका नाटक", "औपनिवेशिक प्रभाव चर्चा"],
    ("11", "Political Science"):["संविधान निर्माण भूमिका नाटक", "अधिकार-कर्तव्य चर्चा", "चुनाव प्रक्रिया अनुकरण", "ऐतिहासिक निर्णय केस स्टडी"],
    ("11", "English"):        ["Photo Essay Writing", "Group Discussion: Human Spirit", "Report Writing Practice", "Poetry Analysis Circle"],
    ("11", "Hindi"):          ["गद्य पाठ विश्लेषण", "पद्य भाव व्याख्या", "संधि-समास अभ्यास", "वाद-विवाद प्रतियोगिता"],
    ("11", "Social Science"):  ["भारत भौतिक नक्शा लेबलिंग", "जलवायु डेटा विश्लेषण", "स्वतंत्रता पूर्व-पश्चात अर्थव्यवस्था तुलना", "मानव विकास सूचकांक"],
    ("11", "General"):        ["न्यूटन नियम प्रदर्शन", "माँग-आपूर्ति वक्र", "कोशिका चित्र लेबलिंग", "Python कैलकुलेटर"],
    ("12", "Physics"):        ["विद्युत क्षेत्र रेखा चित्रण", "परिपथ निर्माण और सत्यापन", "लेंस और दर्पण किरण आरेख", "प्रकाश विद्युत प्रभाव चर्चा"],
    ("12", "Chemistry"):      ["क्रिस्टल संरचना मॉडल", "वैद्युत रासायनिक सेल प्रदर्शन", "अभिक्रिया दर प्रयोग", "उपसहसंयोजन यौगिक मॉडल"],
    ("12", "Biology"):        ["द्विसंकर क्रॉस गतिविधि", "DNA निष्कर्षण प्रदर्शन", "पारिस्थितिकी तंत्र जाल निर्माण", "जैव प्रौद्योगिकी केस स्टडी"],
    ("12", "Mathematics"):    ["आव्यूह संचालन अभ्यास पत्र", "अवकलज अनुप्रयोग: उच्चिष्ठ-निम्निष्ठ", "कार्ड/पासे से प्रायिकता प्रयोग", "प्रतिस्थापन से समाकलन"],
    ("12", "Economics"):      ["GDP गणना गतिविधि", "बजट घाटा विश्लेषण", "व्यापार संतुलन केस स्टडी", "भारत vs चीन विकास तुलना"],
    ("12", "Computer Science"):["नमूना DB पर SQL प्रश्न", "Python में स्टैक कार्यान्वयन", "नेटवर्क टोपोलॉजी चित्रण", "साइबर सुरक्षा केस स्टडी"],
    ("12", "Business Studies"):["प्रबंधन सिद्धांत केस स्टडी (फेयोल)", "विपणन मिश्रण (4P) विश्लेषण", "उपभोक्ता संरक्षण अधिनियम नाटक", "व्यवसाय योजना प्रस्तुति"],
    ("12", "History"):        ["हड़प्पा कलाकृति विश्लेषण", "1857 विद्रोह समयरेखा", "संविधान निर्माण चर्चा", "भक्ति-सूफी आंदोलन तुलना"],
    ("12", "Political Science"):["शीत युद्ध समयरेखा", "संयुक्त राष्ट्र भूमिका नाटक", "भारतीय सामाजिक आंदोलन बहस", "चुनावी राजनीति केस स्टडी"],
    ("12", "English"):        ["Short Story Analysis Circle", "Creative Writing Workshop", "Formal Letter & Report Competition", "Poetry Recitation & Interpretation"],
    ("12", "Hindi"):          ["कहानी की समीक्षा", "काव्यांश व्याख्या", "साहित्यिक वाद-विवाद", "लेखन कौशल अभ्यास"],
    ("12", "Social Science"):  ["वैश्वीकरण बहस", "कृषि परिवर्तन केस स्टडी", "पर्यावरण-समाज चर्चा", "सामाजिक आंदोलन मानचित्रण"],
    ("12", "General"):        ["विद्युत परिपथ निर्माण", "आनुवंशिकता क्रॉस गतिविधि", "अवकलज के अनुप्रयोग प्रश्न", "SQL प्रश्न अभ्यास"],
}


def get_concept_topics(grade: str, subject: str, lang: str = "en") -> list:
    """Return 6 quick topic suggestions for the Concept & Quiz tabs."""
    key = (str(grade), subject)
    if lang == "hi" and subject != "English":
        return (_CONCEPT_TOPICS_HI.get(key)
                or _CONCEPT_TOPICS_HI.get((str(grade), "General"))
                or _CONCEPT_FALLBACK_HI)
    return (_CONCEPT_TOPICS.get(key)
            or _CONCEPT_TOPICS.get((str(grade), "General"))
            or _CONCEPT_FALLBACK)


def get_activity_topics(grade: str, subject: str, lang: str = "en") -> list:
    """Return 4 quick activity suggestions for the Activity tab."""
    key = (str(grade), subject)
    if lang == "hi" and subject != "English":
        return (_ACTIVITY_TOPICS_HI.get(key)
                or _ACTIVITY_TOPICS_HI.get((str(grade), "General"))
                or _ACTIVITY_FALLBACK_HI)
    return (_ACTIVITY_TOPICS.get(key)
            or _ACTIVITY_TOPICS.get((str(grade), "General"))
            or _ACTIVITY_FALLBACK)
